apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dev-rabbitmq
  template:
    metadata:
      labels:
        app: dev-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.13
        ports:
        - containerPort: 5672
          name: rabbitmq
