#!/bin/bash -e
MAIN_DIRECTORY=$(pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null; git rev-parse --show-toplevel; popd > /dev/null)

docker build -t docker.socialwifi.com/sw-cli "$MAIN_DIRECTORY/docker"
