#!/bin/bash
MAIN_DIRECTORY=$(pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null; git rev-parse --show-toplevel; popd > /dev/null)

docker run --rm -v /usr/bin:/installation docker.socialwifi.com/sw-cli install_alias --development-dir=$MAIN_DIRECTORY/docker/source
